language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '13'
script:
  - npm test
  - npm run test-direct
  - npm run test-in-subfolder
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
